# Lima macOS VM Management
# Manages three VM instances: macos-26 (release), macos-26-beta (beta), macos-15 (N-1)

.PHONY: macos-26 run-26 clean-26 macports-26 \
        macos-26-beta run-26-beta clean-26-beta macports-26-beta \
        macos-15 run-15 clean-15 macports-15 \
        register-26 unregister-26 \
        register-26-beta unregister-26-beta \
        register-15 unregister-15 \
        status help

# ── Tool paths ────────────────────────────────────────────────────────────────

LIMACTL      ?= limactl
LIMA_APP_BUNDLE ?= /Applications/MacPorts/Lima.app
GHRUNNER     ?= $(HOME)/Developer/blakeports/scripts/ghrunner

# ── Instance definitions ──────────────────────────────────────────────────────

INSTANCE_26      := macos-26
INSTANCE_26_BETA := macos-26-beta
INSTANCE_15      := macos-15

CONFIG_26      := $(CURDIR)/macos-26.yaml
CONFIG_26_BETA := $(CURDIR)/macos-26-beta.yaml
CONFIG_15      := $(CURDIR)/macos-15.yaml

.DEFAULT_GOAL := help

# ── macOS 26 (release) ────────────────────────────────────────────────────────

macos-26:
	$(LIMACTL) create --tty=false --name=$(INSTANCE_26) $(CONFIG_26)
	$(LIMACTL) start $(INSTANCE_26)
	$(LIMACTL) stop $(INSTANCE_26)

run-26:
	$(LIMACTL) start $(INSTANCE_26)

clean-26:
	-$(LIMACTL) stop -f $(INSTANCE_26)
	$(LIMACTL) remove -f $(INSTANCE_26)

macports-26:
	$(LIMACTL) shell $(INSTANCE_26) /Volumes/lima_mac/macports.sh

# ── macOS 26 Beta ─────────────────────────────────────────────────────────────

macos-26-beta:
	$(LIMACTL) create --tty=false --name=$(INSTANCE_26_BETA) $(CONFIG_26_BETA)
	$(LIMACTL) start $(INSTANCE_26_BETA)
	$(LIMACTL) stop $(INSTANCE_26_BETA)

run-26-beta:
	$(LIMACTL) start $(INSTANCE_26_BETA)

clean-26-beta:
	-$(LIMACTL) stop -f $(INSTANCE_26_BETA)
	$(LIMACTL) remove -f $(INSTANCE_26_BETA)

macports-26-beta:
	$(LIMACTL) shell $(INSTANCE_26_BETA) /Volumes/lima_mac/macports.sh

# ── macOS 15 (Sequoia) ────────────────────────────────────────────────────────

macos-15:
	$(LIMACTL) create --tty=false --name=$(INSTANCE_15) $(CONFIG_15)
	$(LIMACTL) start $(INSTANCE_15)
	$(LIMACTL) stop $(INSTANCE_15)

run-15:
	$(LIMACTL) start $(INSTANCE_15)

clean-15:
	-$(LIMACTL) stop -f $(INSTANCE_15)
	$(LIMACTL) remove -f $(INSTANCE_15)

macports-15:
	$(LIMACTL) shell $(INSTANCE_15) /Volumes/lima_mac/macports.sh

# ── Runner registration ───────────────────────────────────────────────────────
# VM must be running before registering. Token is generated by ghrunner via gh CLI.

register-26:
	$(GHRUNNER) -lima $(INSTANCE_26)

unregister-26:
	$(GHRUNNER) -remove macOS_26

register-26-beta:
	$(GHRUNNER) -lima $(INSTANCE_26_BETA)

unregister-26-beta:
	$(GHRUNNER) -remove macOS_26_beta

register-15:
	$(GHRUNNER) -lima $(INSTANCE_15)

unregister-15:
	$(GHRUNNER) -remove macOS_15

# ── Status and help ───────────────────────────────────────────────────────────

status:
	$(LIMACTL) list

help:
	@echo "Lima macOS VM Management"
	@echo ""
	@echo "Usage: make [target]"
	@echo ""
	@echo "VM lifecycle (run in order for first-time setup):"
	@echo "  macos-26        Create, provision, and stop macOS 26 VM"
	@echo "  run-26          Start macOS 26 VM"
	@echo "  macports-26     Install MacPorts in macOS 26 VM (run once, takes ~10-30 min)"
	@echo "  register-26     Register macOS 26 as GitHub Actions runner"
	@echo "  clean-26        Stop and remove macOS 26 VM"
	@echo ""
	@echo "  macos-26-beta   Create, provision, and stop macOS 26 Beta VM"
	@echo "  run-26-beta     Start macOS 26 Beta VM"
	@echo "  macports-26-beta Install MacPorts in macOS 26 Beta VM (run once)"
	@echo "  register-26-beta Register macOS 26 Beta as GitHub Actions runner"
	@echo "  clean-26-beta   Stop and remove macOS 26 Beta VM"
	@echo ""
	@echo "  macos-15        Create, provision, and stop macOS 15 VM"
	@echo "  run-15          Start macOS 15 VM"
	@echo "  macports-15     Install MacPorts in macOS 15 VM (run once)"
	@echo "  register-15     Register macOS 15 as GitHub Actions runner"
	@echo "  clean-15        Stop and remove macOS 15 VM"
	@echo ""
	@echo "Runner de-registration:"
	@echo "  unregister-26      De-register macOS 26 runner from GitHub"
	@echo "  unregister-26-beta De-register macOS 26 Beta runner from GitHub"
	@echo "  unregister-15      De-register macOS 15 runner from GitHub"
	@echo ""
	@echo "Other:"
	@echo "  status          Show all Lima instance states"
	@echo "  help            Show this message"
	@echo ""
	@echo "Overridable variables:"
	@echo "  LIMACTL=$(LIMACTL)"
	@echo "  LIMA_APP_BUNDLE=$(LIMA_APP_BUNDLE)"
	@echo "  GHRUNNER=$(GHRUNNER)"
